### ISSUE TITLE
Storing weight vectors

### ISSUE THREAD

**Issue by dr-stringfellow** [PandaPhysics/OldPandaProd#12]
Let's store the first 9 weights for each file where the vector is present, and the entire weight vector for signal samples (need a flag for that to tell crab).
In addition, we need to save the names of the weights as another vector on a per-file-basis (not per-event to limit the size of the output).

**Comment by sidnarayanan** [comment]
Scale shifts were implemented in #20

**Comment by sidnarayanan** [comment]
I think we should move `mcWeight` from `PEvent`/`EventFiller` to `PGenInfo`/`GenInfoFiller`, for consolidation of related information
