### ISSUE TITLE
JSON?

### ISSUE THREAD

**Issue by sidnarayanan** [PandaPhysics/OldPandaProd#14]
The CMSSW config `runNtupler.py` can be told what JSON to apply to data. This is effectively what CRAB does when you supply a JSON. Should this be configured for production when Christoph runs? I know he prefers to run without a JSON, but I'm wondering how useful that is right now, when a JSON is well-established. Applying it at the production step also means not having to check when doing the analysis, which is an extra computation (the way I do it is building a map run -> list of good lumis, maybe this is not very efficient)

Any thoughts @maierbenedikt @yiiyama ?

**Comment by yiiyama** [comment]
We should have a simple EDFilter to select good lumis if such a module does not exist in CMSSW (It's very likely there is one already).
But then I would say it's technically a bit complicated to use the module under the current model, where monolithic samples are produced "centrally" by Christoph's machinery automatically. You would have to somehow tell the production framework to use specific JSON files for specific datasets.
Whether the current model is best fit for panda is still an open question though.

**Comment by sidnarayanan** [comment]
Seems like production is running without a JSON, so I'm closing this.
